// Code generated by cli/hack/buildskills. DO NOT EDIT.

package skills

import "embed"

// FS contains the embedded CLI skill documentation.
//go:embed comments docs live privacy proof recipe-sightmap-setup review shared sightmap tunnel
var FS embed.FS
